[2024-02-17T14:41:09.659+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2024-02-17T14:41:08.480871+00:00 [queued]>
[2024-02-17T14:41:09.664+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2024-02-17T14:41:08.480871+00:00 [queued]>
[2024-02-17T14:41:09.664+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-17T14:41:09.671+0000] {taskinstance.py:2192} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2024-02-17 14:41:08.480871+00:00
[2024-02-17T14:41:09.675+0000] {standard_task_runner.py:60} INFO - Started process 17045 to run task
[2024-02-17T14:41:09.680+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Stage_events', 'manual__2024-02-17T14:41:08.480871+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpdeb45ilr']
[2024-02-17T14:41:09.685+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask Stage_events
[2024-02-17T14:41:09.726+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Stage_events manual__2024-02-17T14:41:08.480871+00:00 [running]> on host 6b28116ad14a
[2024-02-17T14:41:09.765+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T14:41:08.480871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-17T14:41:08.480871+00:00'
[2024-02-17T14:41:09.771+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-17T14:41:09.772+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-17T14:41:09.778+0000] {stage_redshift.py:48} INFO - Drop table staging.staging_events from destination Redshift table
[2024-02-17T14:41:09.781+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-17T14:41:17.794+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/stage_redshift.py", line 49, in execute
    redshift.run(f"Drop table if exists {self.schema}.{self.table}")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "default-workgroup.509716464406.us-east-1.redshift-serverless.amazonaws.com" to address: Temporary failure in name resolution

[2024-02-17T14:41:17.825+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_project, task_id=Stage_events, execution_date=20240217T144108, start_date=20240217T144109, end_date=20240217T144117
[2024-02-17T14:41:17.840+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task Stage_events (could not translate host name "default-workgroup.509716464406.us-east-1.redshift-serverless.amazonaws.com" to address: Temporary failure in name resolution
; 17045)
[2024-02-17T14:41:17.874+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-17T14:41:17.887+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
