[2024-02-18T07:55:15.684+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Stage_songs manual__2024-02-18T07:54:39.290957+00:00 [queued]>
[2024-02-18T07:55:15.688+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Stage_songs manual__2024-02-18T07:54:39.290957+00:00 [queued]>
[2024-02-18T07:55:15.689+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-18T07:55:15.696+0000] {taskinstance.py:2192} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2024-02-18 07:54:39.290957+00:00
[2024-02-18T07:55:15.699+0000] {standard_task_runner.py:60} INFO - Started process 22276 to run task
[2024-02-18T07:55:15.703+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Stage_songs', 'manual__2024-02-18T07:54:39.290957+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpwsy6dpw6']
[2024-02-18T07:55:15.705+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask Stage_songs
[2024-02-18T07:55:15.731+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Stage_songs manual__2024-02-18T07:54:39.290957+00:00 [running]> on host 6b28116ad14a
[2024-02-18T07:55:15.770+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T07:54:39.290957+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T07:54:39.290957+00:00'
[2024-02-18T07:55:15.777+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-18T07:55:15.777+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-18T07:55:15.784+0000] {stage_redshift.py:49} INFO - Copying data from S3 to Redshift
[2024-02-18T07:55:15.784+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.785+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.785+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.786+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.786+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.786+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.787+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.787+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.787+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.787+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.788+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.788+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T07:55:15.792+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T07:55:23.274+0000] {sql.py:432} INFO - Running statement: 
         copy staging.staging_songs from 's3://ericliu-udacity-lake-house/log-data'  
         format as json 'auto'
         ACCESS_KEY_ID 'AKIAXNLLYAMLPRRBUZMF'
        SECRET_ACCESS_KEY '***';
        , parameters: None
[2024-02-18T07:55:31.322+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/stage_redshift.py", line 60, in execute
    redshift.run(formatted_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: Load into table 'staging_songs' failed.  Check 'sys_load_error_detail' system table for details.

[2024-02-18T07:55:31.328+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_project, task_id=Stage_songs, execution_date=20240218T075439, start_date=20240218T075515, end_date=20240218T075531
[2024-02-18T07:55:31.334+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task Stage_songs (Load into table 'staging_songs' failed.  Check 'sys_load_error_detail' system table for details.
; 22276)
[2024-02-18T07:55:31.377+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T07:55:31.386+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
